### ISSUE TITLE
[bug] TypeError: Cannot set property '' of undefined

### ISSUE THREAD

**Issue by florianlenz** [stefanpenner/es6-promise#316]
Hi, 

I have a bug with es6-promise in my react-native project an I am not sure how to solve it. I am even not sure if it's a real bug or my fault since the error message is meaningless to me.  The bug doesn't appear on my macbook but on linux, for that i provided an docker setup. 

Here is the error:

```
TypeError: Cannot set property '' of undefined

      at Promise (node_modules/es6-promise/dist/es6-promise.js:879:22)
      at Function.memoisePluginContainer (node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
      at Function.normalisePlugin (node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
          at Array.map (<anonymous>)
      at Function.normalisePlugins (node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
      at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
      at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
      at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
      at new File (node_modules/babel-core/lib/transformation/file/index.js:135:24)
```

It's an open source project so you might want to have a look at it your self: 

1. clone the repo: `git clone git@github.com:Bit-Nation/BITNATION-Pangea-mobile.git"``
2. Checkout this commit `git checkout 75464e175770712bdd63b6b57a0ad06eca69a9d5`
3. install npm modules `npm install`
4. start the docker container `docker-compose up -d`
5. enter the docker container `docker-compose exec node bash`
6. exec all the tests `node_modules/.bin/jest`

**Comment by stefanpenner** [comment]
@bekzod got any free cycles to investigate?
